codium --user-data-dir .vscode

codium --install-extension abusaidm.html-snippets
codium --install-extension antfu.browse-lite
codium --install-extension antfu.vite
codium --install-extension bungcip.better-toml
codium --install-extension donjayamanne.githistory
codium --install-extension ecmel.vscode-html-css
codium --install-extension James-Yu.latex-workshop
codium --install-extension ms-vscode.powershell
codium --install-extension ms-vscode.vscode-typescript-tslint-plugin
codium --install-extension nopeslide.vscode-drawio-plugin-rtl
codium --install-extension oderwat.indent-rainbow
codium --install-extension paragdiwan.gitpatch
codium --install-extension phil294.git-log--graph
codium --install-extension pomdtr.excalidraw-editor
codium --install-extension rust-lang.rust-analyzer
codium --install-extension s-nlf-fh.glassit
codium --install-extension streetsidesoftware.code-spell-checker
codium --install-extension Sudhan.neondark-theme
codium --install-extension TheNuProjectContributors.vscode-nushell-lang
codium --install-extension tomoki1207.pdf
codium --install-extension vadimcn.vscode-lldb
codium --install-extension Vue.volar
codium --install-extension xabikos.JavaScriptSnippets
codium --install-extension yoavbls.pretty-ts-errors